// Admin-only settings API for the self-service Website Lead Form connection: generate/rotate
// the API key, and toggle whether the public endpoint accepts submissions. See lib/websiteLeads.js
// for storage and app/api/leads/website/route.js for the endpoint the key actually protects.
import { getEmployee } from '@/lib/auth';
import { getWebsiteLeadSettings, saveWebsiteLeadSettings, generateApiKey } from '@/lib/websiteLeads';

export const dynamic = 'force-dynamic';

async function requireAdmin() {
  const employee = await getEmployee();
  if (!employee || employee.role !== 'admin') return null;
  return employee;
}

// Unlike the Meta Page token, this key is generated BY Heseos BOS for the admin to hand out —
// it's not a third-party secret being proxied, so it's safe (and useful) to keep showing it
// back to the admin rather than a one-time reveal.
function endpointUrl() {
  const base = (process.env.PUBLIC_BASE_URL || '').replace(/\/$/, '');
  return `${base}/api/leads/website`;
}

function publicSettings(settings) {
  if (!settings || !settings.apiKey) {
    return { connected: false, apiKey: null, enabled: false, endpointUrl: endpointUrl() };
  }
  return { connected: true, apiKey: settings.apiKey, enabled: settings.enabled !== false, createdAt: settings.createdAt || null, regeneratedAt: settings.regeneratedAt || null, endpointUrl: endpointUrl() };
}

export async function GET() {
  const admin = await requireAdmin();
  if (!admin) return Response.json({ error: 'Unauthorized' }, { status: 401 });
  const settings = await getWebsiteLeadSettings();
  return Response.json(publicSettings(settings));
}

// POST — first-time setup: generate a key and turn capture on.
export async function POST() {
  const admin = await requireAdmin();
  if (!admin) return Response.json({ error: 'Unauthorized' }, { status: 401 });
  const existing = await getWebsiteLeadSettings();
  const settings = await saveWebsiteLeadSettings({
    apiKey: generateApiKey(),
    enabled: true,
    createdAt: existing?.createdAt || new Date().toISOString(),
    createdBy: admin.id,
  });
  return Response.json(publicSettings(settings));
}

// PATCH { action: 'regenerate' } — invalidate the old key (anyone still using it starts
// getting 401s) and hand back a fresh one; the admin re-shares it with whoever runs the site.
// PATCH { enabled: boolean } — pause/resume capture without touching the key.
export async function PATCH(request) {
  const admin = await requireAdmin();
  if (!admin) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  const existing = await getWebsiteLeadSettings();
  if (!existing || !existing.apiKey) {
    return Response.json({ error: 'Generate a key first.' }, { status: 400 });
  }

  const body = await request.json().catch(() => ({}));

  if (body.action === 'regenerate') {
    const settings = await saveWebsiteLeadSettings({ apiKey: generateApiKey(), regeneratedAt: new Date().toISOString() });
    return Response.json(publicSettings(settings));
  }

  if (typeof body.enabled === 'boolean') {
    const settings = await saveWebsiteLeadSettings({ enabled: body.enabled });
    return Response.json(publicSettings(settings));
  }

  return Response.json({ error: 'Nothing to update.' }, { status: 400 });
}
