// Lead-conversion payout engine — an admin-configured tiered commission structure (Settings →
// Lead Conversion Payout, components/admin/SettingsPage.jsx's PayoutSettingsCard) with its OWN
// independent tier ladder and on/off switch for each of the three ways a lead gets referred in:
// a partner (any lead with partnerId set, whichever channel — Partner App punch, QR scan, or
// referral link), an employee (a lead they punched in themselves via the Team App —
// addedByEmployeeId), and a customer referrer (a lead attributed to their own referral_customer
// link — attributionLinkId; no live UI creates these links yet, see app/api/admin/attribution's
// header comment, but the engine already supports the category for whenever that flow exists).
// All three share the same payout PERIOD (monthly/quarterly) — see PAYOUT_CATEGORIES below for
// the full category list and PAYOUT_CATEGORY_META for their admin-facing labels.
//
// Design, spelled out (see also lib/payoutSettings.js for how the config itself is stored):
//
//  - PERIOD: the admin picks 'monthly' or 'quarterly', shared across every category. Every
//    payout is computed for the period containing "now" (IST) — there's no historical period
//    picker; this mirrors the "This Month" framing the old mock earnings already used.
//  - SALE VALUE: the only leads that count are ones that have actually closed — stageOf(lead)
//    === 'Converted' (lib/leadStage.js) — and the amount counted is lead.finalPrice, the real
//    negotiated closing price (never quotationAmount, which is only ever a pre-negotiation
//    estimate — see lib/adminMetrics.js's header comment). A lead only counts toward a period
//    if it CONVERTED within that period (convertedAt), not merely created within it — matches
//    how lib/adminMetrics.js's revenueByMonth already buckets "when the money counts."
//  - TIER LOOKUP: PROGRESSIVE ("tax slab") brackets, scoped to ONE category's own ladder — the
//    same mechanic as an income-tax slab, just with rates that typically step DOWN instead of
//    up (a bigger deal earns less on the portion above each threshold, never less on the whole
//    deal). Tiers are sorted ascending by their upper bound (upTo); each tier's rate applies
//    ONLY to the slice of the referrer's period total that falls within that tier's own range —
//    never to the whole total. E.g. tiers [≤25,00,000 → 15%, ≤75,00,000 → 10%, unbounded → 8%]
//    and a ₹90,00,000 total pays 15% of the first ₹25L, PLUS 10% of the next ₹50L, PLUS 8% of
//    the remaining ₹15L — see slabPayoutFor(). Selling more can only ever raise the total
//    payout; it just raises it at a slower marginal rate past each threshold, which is why
//    tierInfoFor()'s `rate` (the marginal rate on the NEXT rupee) and payoutFor()'s
//    `effectiveRate` (the blended rate actually being paid on the WHOLE total) are two
//    different numbers, and both worth showing — see the Partner/Team Rewards screens.
//  - ENABLED: each category can be switched off independently (e.g. customer referrals not
//    live yet) — a disabled category behaves as if it has no tiers (rate 0, hasTiers false),
//    but payoutFor()'s `enabled` field lets a consumer show "this isn't turned on" rather than
//    "no tiers configured yet."
//  - WHO COUNTS AS "THIS REFERRER'S" LEADS is the caller's job, not this module's — pass in an
//    already-filtered list (e.g. leads.filter(l => l.partnerId === partner.id)) plus which
//    category's ladder applies, exactly the same style every other per-referrer stat in this
//    codebase already uses (lib/adminMetrics.js's partnerStats/engineerStats/presalesStats).
//    This keeps the engine itself referrer-agnostic.
//
// Pure, no I/O — safe to import from both server code and 'use client' components (the actual
// config is read/written through lib/payoutSettings.js on the server and the read-only
// /api/payout-settings route on the client).

import { stageOf } from '@/lib/leadStage';

export const PAYOUT_CATEGORIES = ['partner', 'employee', 'customer'];

// Admin-facing copy for each category's card — components/admin/SettingsPage.jsx's
// PayoutSettingsCard renders one card per entry, in this order.
export const PAYOUT_CATEGORY_META = {
  partner: { title: 'Leads by Partner', sub: 'Payout for leads generated by partners.' },
  employee: { title: 'Leads by Employees', sub: 'Payout for leads added by employees.' },
  customer: { title: 'Leads by Customer', sub: 'Payout for customer referrals.' },
};

export const DEFAULT_PAYOUT_CONFIG = {
  period: 'monthly',
  categories: Object.fromEntries(PAYOUT_CATEGORIES.map((k) => [k, { enabled: true, tiers: [] }])),
};

// Tiers as stored/edited: { upTo: number|null, rate: number }. `upTo` null means "no upper
// bound" — the open-ended top tier. Sorted ascending by upTo, with null (unbounded) sorted last;
// if more than one tier is left unbounded (a config mistake), the earliest one in that order
// wins for any total that reaches it, since tier lookup returns on first match.
export function normalizeTiers(tiers) {
  if (!Array.isArray(tiers)) return [];
  return tiers
    .map((t) => ({
      upTo: t && t.upTo !== '' && t.upTo != null ? Number(t.upTo) : null,
      rate: Math.max(0, Number(t?.rate) || 0),
    }))
    .filter((t) => t.upTo === null || (Number.isFinite(t.upTo) && t.upTo > 0))
    .sort((a, b) => (a.upTo === null ? Infinity : a.upTo) - (b.upTo === null ? Infinity : b.upTo));
}

// Defends every consumer against a not-yet-loaded / malformed config — useApiResource
// (lib/useApiResource.js) defaults an unfetched GET to `[]`, not `{}`, so every reader of
// /api/payout-settings should normalize through here rather than trust the raw shape.
//
// One-time migration: a config saved before per-category tiers existed stored a single flat
// `tiers` array (no `categories` key at all). When we see that old shape, seed every category's
// ladder with that same list rather than silently dropping it — matches the original design's
// intent ("one fixed payout structure... applicable to everyone") on the first load after the
// upgrade; the admin can then split them apart from Settings going forward.
export function normalizeConfig(raw) {
  const period = raw && raw.period === 'quarterly' ? 'quarterly' : 'monthly';
  const legacyTiers = raw && !raw.categories && Array.isArray(raw.tiers) ? normalizeTiers(raw.tiers) : null;
  const categories = {};
  for (const key of PAYOUT_CATEGORIES) {
    const rawCat = raw && raw.categories ? raw.categories[key] : null;
    categories[key] = {
      enabled: rawCat ? rawCat.enabled !== false : true,
      tiers: rawCat ? normalizeTiers(rawCat.tiers) : (legacyTiers || []),
    };
  }
  return { period, categories };
}

// Calendar bounds (as Date instants) of the period containing `ref`, computed in IST — Heseos
// operates in India (see lib/date.js's header) and every payout period should line up with the
// calendar month/quarter an Indian admin actually means, not the server's UTC day.
export function periodBounds(period, ref = new Date()) {
  const ist = new Date(ref.toLocaleString('en-US', { timeZone: 'Asia/Kolkata' }));
  const y = ist.getFullYear();
  const m = ist.getMonth();
  if (period === 'quarterly') {
    const qStart = Math.floor(m / 3) * 3;
    return { start: new Date(y, qStart, 1), end: new Date(y, qStart + 3, 1) };
  }
  return { start: new Date(y, m, 1), end: new Date(y, m + 1, 1) };
}

// A short, human label for the period containing `ref` — "September 2026" or "Q3 2026".
export function periodLabel(period, ref = new Date()) {
  const ist = new Date(ref.toLocaleString('en-US', { timeZone: 'Asia/Kolkata' }));
  if (period === 'quarterly') {
    const q = Math.floor(ist.getMonth() / 3) + 1;
    return `Q${q} ${ist.getFullYear()}`;
  }
  return ist.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
}

// Which tier a total value falls into (flat/slab — see file header), plus the next tier up (for
// a "₹X more to reach Y%" progress nudge) and how much more total value is needed to cross into
// it. tiers must already be normalizeTiers()'d (ascending, null-upTo last).
export function tierInfoFor(tiers, totalValue) {
  if (!tiers || tiers.length === 0) return { rate: 0, index: -1, current: null, next: null, remainingToNext: null };
  let index = tiers.findIndex((t) => t.upTo === null || totalValue <= t.upTo);
  if (index === -1) index = tiers.length - 1; // shouldn't happen (last tier is usually unbounded), but never fall through with no match
  const current = tiers[index];
  const next = tiers[index + 1] || null;
  const remainingToNext = next && current.upTo !== null ? Math.max(0, current.upTo - totalValue) : null;
  return { rate: current.rate, index, current, next, remainingToNext };
}

// The actual progressive ("tax slab") payout on `totalValue` — see file header. Walks the
// tiers in ascending order, taxing only the slice of value that falls within each one, and
// sums the result; a single `Math.round` at the very end (not per-slice) avoids compounding
// paisa-rounding error across tiers. Also returns the EFFECTIVE rate (payout ÷ totalValue, as
// a %) — the blended rate actually being earned on the whole total, distinct from
// tierInfoFor()'s marginal rate — and a per-tier breakdown for display (how much of the total
// fell in each tier, and how much that tier alone contributed to the payout).
export function slabPayoutFor(tiers, totalValue) {
  const value = Math.max(0, Number(totalValue) || 0);
  const breakdown = [];
  let prevUpTo = 0;
  let rawPaise = 0; // value*rate units (rupees × percentage-points); /100 once at the end
  for (const t of tiers || []) {
    const upTo = t.upTo === null ? Infinity : t.upTo;
    const sliceValue = Math.max(0, Math.min(value, upTo) - prevUpTo);
    if (sliceValue > 0) {
      const slicePayout = Math.round(sliceValue * t.rate) / 100;
      rawPaise += sliceValue * t.rate;
      breakdown.push({ upTo: t.upTo, rate: t.rate, sliceValue, slicePayout });
    }
    prevUpTo = upTo;
    if (value <= upTo) break;
  }
  const payout = Math.round(rawPaise) / 100;
  const effectiveRate = value > 0 ? Math.round((payout / value) * 10000) / 100 : 0;
  return { payout, effectiveRate, breakdown };
}

// The value of a lead toward payout tiering: only converted leads have one at all.
export function leadSaleValue(lead) {
  if (!lead || stageOf(lead) !== 'Converted' || lead.finalPrice == null) return 0;
  return Number(lead.finalPrice) || 0;
}

// The full payout computation for one referrer's already-filtered lead list, against ONE
// category's ladder ('partner' | 'employee' | 'customer'), for the period containing `ref`
// (defaults to now). See file header for the exact rules being applied.
export function payoutFor(leads, rawConfig, category = 'partner', ref = new Date()) {
  const config = normalizeConfig(rawConfig);
  const cat = config.categories[category] || DEFAULT_PAYOUT_CONFIG.categories.partner;
  const { start, end } = periodBounds(config.period, ref);
  let totalValue = 0;
  let convertedCount = 0;
  for (const l of leads || []) {
    const value = leadSaleValue(l);
    if (value <= 0) continue;
    const convertedAt = l.convertedAt ? new Date(l.convertedAt) : null;
    if (!convertedAt || convertedAt < start || convertedAt >= end) continue;
    totalValue += value;
    convertedCount += 1;
  }
  const tiers = cat.enabled ? cat.tiers : [];
  const info = tierInfoFor(tiers, totalValue); // marginal tier — rate on the NEXT rupee, "how much more to next bracket"
  const slab = slabPayoutFor(tiers, totalValue); // the actual progressive payout total + blended rate
  return {
    category,
    enabled: cat.enabled,
    period: config.period,
    periodLabel: periodLabel(config.period, ref),
    periodStart: start,
    periodEnd: end,
    totalValue,
    convertedCount,
    rate: info.rate,
    effectiveRate: slab.effectiveRate,
    payout: slab.payout,
    tierBreakdown: slab.breakdown,
    hasTiers: tiers.length > 0,
    tierIndex: info.index,
    nextTier: info.next,
    remainingToNextTier: info.remainingToNext,
    tiers,
  };
}
