// Admin backend for QR codes & referral links — see lib/attribution.js for the model.
// GET   — every attribution link + its funnel (scans/leads/converted), for the Growth tab table.
//         Deliberately excludes kind 'referral_customer' — those are self-generated by the
//         customer (eventually via the WhatsApp bot) and don't belong in this admin-curated
//         list; they'll get their own place once that flow exists.
// POST  — create a new qr_location link. That's the only kind still created here: qr_partner
//         codes are pre-printed in bulk instead (see app/api/admin/attribution/blank-qr and
//         lib/attribution.js's createBlankPartnerQrCodes) and claimed by the partner themselves
//         from a physical sticker, and referral_partner is self-provisioned by the partner (see
//         app/api/partner/attribution) — referral_customer is rejected entirely, customers will
//         generate their own from the WhatsApp bot, not through here.
// PATCH — toggle a link active/inactive (never delete: history — visits/leads — must stay
//         attributable even after a placement comes down or a promo ends).

import { dbList, dbPatch } from '@/lib/db';
import { getEmployee } from '@/lib/auth';
import { createAttributionLink, funnelForAll, getHeseosBotTenant, buildWaLink } from '@/lib/attribution';

export const dynamic = 'force-dynamic';

// Prefer a direct https://wa.me/<number>?text=...(ref:<code>) link straight into Heseos Buddy
// (buildWaLink) over the tracked /go/<code> redirector — scanning/tapping opens WhatsApp
// immediately instead of bouncing through our own domain first. Only falls back to /go/<code>
// when WhatsApp isn't connected/verified yet, since that page's own friendly message is a
// better dead end than a broken wa.me link — and it resolves correctly the moment it is
// connected. See app/api/partner/attribution/route.js for the same logic, and its header
// comment for why losing the tracked hop doesn't affect lead/conversion attribution.
function linkUrlFor(tenant, code) {
  return (tenant ? buildWaLink(tenant, code) : null) || null;
}

export async function GET() {
  const employee = await getEmployee();
  if (!employee) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  const [allLinks, partners, tenant] = await Promise.all([dbList('attribution_links'), dbList('partners'), getHeseosBotTenant()]);
  const links = allLinks.filter((l) => l.kind !== 'referral_customer');
  const funnels = await funnelForAll(links.map((l) => l.id));
  const partnerName = Object.fromEntries(partners.map((p) => [p.id, p.businessName || p.name || p.id]));

  const out = links.map((l) => ({
    ...l,
    partnerName: l.partnerId ? (partnerName[l.partnerId] || l.partnerId) : null,
    url: linkUrlFor(tenant, l.id),
    funnel: funnels.get(l.id) || { visits: 0, leads: 0, converted: 0 },
  }));
  return Response.json(out);
}

// Every location QR needs both a label (what it's called on the table/print sheet) and a
// pincode (which area it's actually placed in, for reporting by area later) — see
// lib/attribution.js's createAttributionLink.
const PINCODE_RE = /^\d{6}$/;

export async function POST(request) {
  const employee = await getEmployee();
  if (!employee) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  const body = await request.json().catch(() => ({}));
  const { kind } = body;

  // Only qr_location is creatable from here — see the file header comment above.
  if (kind !== 'qr_location') {
    return Response.json({ error: kind === 'qr_partner'
      ? 'Partner QR codes are pre-printed in bulk and claimed by the partner — see "Pre-Print Partner QR Codes".'
      : kind === 'referral_customer'
        ? 'Customer referral links are self-generated by the customer, not created here.'
        : 'Only a Location QR code can be created here; referral links are self-service.' }, { status: 400 });
  }

  // `locations`: an array of { label, city, locality, pincode } — one row per QR code, so the
  // Growth tab's "Create Location QR" modal can create a whole batch (every standee going out
  // this week) in a single save instead of reopening the modal per location.
  const locations = Array.isArray(body.locations) ? body.locations : [];
  if (!locations.length) {
    return Response.json({ error: 'At least one location is required' }, { status: 400 });
  }
  if (locations.length > 100) {
    return Response.json({ error: 'Create at most 100 at a time — run it again for a bigger batch' }, { status: 400 });
  }
  for (const loc of locations) {
    const label = String(loc?.label || '').trim();
    if (!label) {
      return Response.json({ error: 'Every location needs a label (e.g. "Koramangala Billboard")' }, { status: 400 });
    }
    if (!String(loc?.city || '').trim()) {
      return Response.json({ error: `A city is required for "${label}"` }, { status: 400 });
    }
    if (!String(loc?.locality || '').trim()) {
      return Response.json({ error: `A locality is required for "${label}"` }, { status: 400 });
    }
    if (!PINCODE_RE.test(String(loc?.pincode || '').trim())) {
      return Response.json({ error: `A 6-digit pincode is required for "${label}"` }, { status: 400 });
    }
  }

  const tenant = await getHeseosBotTenant();
  const created = [];
  for (const loc of locations) {
    // Sequential, not Promise.all — createAttributionLink/generateUniqueCode do their own
    // existence check per attempt, and a batch from one admin request has no real concurrency
    // to worry about; keeping it sequential just avoids hammering the DB.
    // eslint-disable-next-line no-await-in-loop
    const link = await createAttributionLink({
      kind: 'qr_location',
      label: String(loc.label).trim(),
      city: String(loc.city).trim(),
      locality: String(loc.locality).trim(),
      pincode: String(loc.pincode).trim(),
      createdBy: `employee:${employee.id}`,
    });
    created.push({ ...link, url: linkUrlFor(tenant, link.id) });
  }
  return Response.json(created, { status: 201 });
}

export async function PATCH(request) {
  const employee = await getEmployee();
  if (!employee) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  const body = await request.json().catch(() => ({}));
  const { id, active } = body;
  if (!id) return Response.json({ error: 'id is required' }, { status: 400 });

  const patch = {};
  if (active !== undefined) patch.active = !!active;
  if (Object.keys(patch).length === 0) return Response.json({ error: 'Nothing to update' }, { status: 400 });

  const updated = await dbPatch('attribution_links', id, patch);
  if (!updated) return Response.json({ error: 'Not found' }, { status: 404 });
  return Response.json(updated);
}
