// Admin backend for QR codes & referral links — see lib/attribution.js for the model.
// GET  — every attribution link + its funnel (scans/leads/converted), for the Growth tab table.
//        Deliberately excludes kind 'referral_customer' — those are self-generated by the
//        customer (eventually via the WhatsApp bot) and don't belong in this admin-curated
//        list; they'll get their own place once that flow exists.
// POST — create a new link. Only qr_location and qr_partner are creatable here — QR codes need
//        printing/placing, so admin has a hand in both. referral_partner is self-provisioned by
//        the partner (see app/api/partner/attribution), and referral_customer is rejected
//        entirely — customers will generate their own from the WhatsApp bot, not through here.
// PATCH — toggle a link active/inactive (never delete: history — visits/leads — must stay
//         attributable even after a placement comes down or a promo ends).

import { dbGetById, dbList, dbPatch } from '@/lib/db';
import { getEmployee } from '@/lib/auth';
import { createAttributionLink, funnelForAll, getHeseosBotTenant, buildWaLink } from '@/lib/attribution';

export const dynamic = 'force-dynamic';

// Prefer a direct https://wa.me/<number>?text=...(ref:<code>) link straight into Heseos Buddy
// (buildWaLink) over the tracked /go/<code> redirector — scanning/tapping opens WhatsApp
// immediately instead of bouncing through our own domain first. Only falls back to /go/<code>
// when WhatsApp isn't connected/verified yet, since that page's own friendly message is a
// better dead end than a broken wa.me link — and it resolves correctly the moment it is
// connected. See app/api/partner/attribution/route.js for the same logic, and its header
// comment for why losing the tracked hop doesn't affect lead/conversion attribution.
function linkUrlFor(tenant, code) {
  return (tenant ? buildWaLink(tenant, code) : null) || null;
}

export async function GET() {
  const employee = await getEmployee();
  if (!employee) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  const [allLinks, partners, tenant] = await Promise.all([dbList('attribution_links'), dbList('partners'), getHeseosBotTenant()]);
  const links = allLinks.filter((l) => l.kind !== 'referral_customer');
  const funnels = await funnelForAll(links.map((l) => l.id));
  const partnerName = Object.fromEntries(partners.map((p) => [p.id, p.businessName || p.name || p.id]));

  const out = links.map((l) => ({
    ...l,
    partnerName: l.partnerId ? (partnerName[l.partnerId] || l.partnerId) : null,
    url: linkUrlFor(tenant, l.id),
    funnel: funnels.get(l.id) || { visits: 0, leads: 0, converted: 0 },
  }));
  return Response.json(out);
}

export async function POST(request) {
  const employee = await getEmployee();
  if (!employee) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  const body = await request.json().catch(() => ({}));
  const { kind, label, partnerId } = body;

  // Only these two are creatable from Admin — see the file header comment above.
  if (kind !== 'qr_location' && kind !== 'qr_partner') {
    return Response.json({ error: kind === 'referral_customer'
      ? 'Customer referral links are self-generated by the customer, not created here.'
      : 'Only QR — Location and QR — Partner can be created here; referral links are self-service.' }, { status: 400 });
  }

  if (kind === 'qr_partner' && !partnerId) {
    return Response.json({ error: 'partnerId is required for a partner QR code' }, { status: 400 });
  }
  if (kind === 'qr_location' && !String(label || '').trim()) {
    return Response.json({ error: 'A location label is required (e.g. "Koramangala Billboard")' }, { status: 400 });
  }

  let resolvedPartnerId = partnerId || null;
  let resolvedLabel = label || '';
  if (kind === 'qr_partner' && resolvedPartnerId) {
    const partner = await dbGetById('partners', resolvedPartnerId);
    if (!partner) return Response.json({ error: 'Partner not found' }, { status: 404 });
    if (!resolvedLabel) resolvedLabel = partner.businessName || partner.name || partner.id;
  }

  const link = await createAttributionLink({
    kind,
    label: resolvedLabel,
    partnerId: resolvedPartnerId,
    createdBy: `employee:${employee.id}`,
  });
  const tenant = await getHeseosBotTenant();
  return Response.json({ ...link, url: linkUrlFor(tenant, link.id) }, { status: 201 });
}

export async function PATCH(request) {
  const employee = await getEmployee();
  if (!employee) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  const body = await request.json().catch(() => ({}));
  const { id, active } = body;
  if (!id) return Response.json({ error: 'id is required' }, { status: 400 });

  const patch = {};
  if (active !== undefined) patch.active = !!active;
  if (Object.keys(patch).length === 0) return Response.json({ error: 'Nothing to update' }, { status: 400 });

  const updated = await dbPatch('attribution_links', id, patch);
  if (!updated) return Response.json({ error: 'Not found' }, { status: 404 });
  return Response.json(updated);
}
