// Admin-only settings API for the self-service Google Ads Lead Form connection: generate/rotate
// the webhook key, and toggle whether the webhook accepts submissions. See lib/googleAdsLeads.js
// for storage and app/api/leads/google-ads-webhook/route.js for the endpoint the key protects.
import { getEmployee } from '@/lib/auth';
import { getGoogleAdsLeadSettings, saveGoogleAdsLeadSettings, generateWebhookKey } from '@/lib/googleAdsLeads';

export const dynamic = 'force-dynamic';

async function requireAdmin() {
  const employee = await getEmployee();
  if (!employee || employee.role !== 'admin') return null;
  return employee;
}

// Same reasoning as the Website Lead Form's key: this is generated BY Heseos BOS for the admin
// to hand out (to Google Ads' own UI, in this case), not a third-party secret being proxied —
// safe to keep showing back to the admin rather than a one-time reveal.
function webhookUrl() {
  const base = (process.env.PUBLIC_BASE_URL || '').replace(/\/$/, '');
  return `${base}/api/leads/google-ads-webhook`;
}

function publicSettings(settings) {
  if (!settings || !settings.webhookKey) {
    return { connected: false, webhookKey: null, enabled: false, webhookUrl: webhookUrl() };
  }
  return {
    connected: true, webhookKey: settings.webhookKey, enabled: settings.enabled !== false,
    createdAt: settings.createdAt || null, regeneratedAt: settings.regeneratedAt || null,
    leadsReceived: settings.leadsReceived || 0, lastLeadAt: settings.lastLeadAt || null,
    webhookUrl: webhookUrl(),
  };
}

export async function GET() {
  const admin = await requireAdmin();
  if (!admin) return Response.json({ error: 'Unauthorized' }, { status: 401 });
  const settings = await getGoogleAdsLeadSettings();
  return Response.json(publicSettings(settings));
}

// POST — first-time setup: generate a key and turn capture on.
export async function POST() {
  const admin = await requireAdmin();
  if (!admin) return Response.json({ error: 'Unauthorized' }, { status: 401 });
  const existing = await getGoogleAdsLeadSettings();
  const settings = await saveGoogleAdsLeadSettings({
    webhookKey: generateWebhookKey(),
    enabled: true,
    createdAt: existing?.createdAt || new Date().toISOString(),
    createdBy: admin.id,
  });
  return Response.json(publicSettings(settings));
}

// PATCH { action: 'regenerate' } — invalidate the old key (Google Ads keeps sending it, and
// every call gets rejected until the admin updates it in each Lead Form asset's Delivery
// settings) and hand back a fresh one.
// PATCH { enabled: boolean } — pause/resume capture without touching the key.
export async function PATCH(request) {
  const admin = await requireAdmin();
  if (!admin) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  const existing = await getGoogleAdsLeadSettings();
  if (!existing || !existing.webhookKey) {
    return Response.json({ error: 'Generate a key first.' }, { status: 400 });
  }

  const body = await request.json().catch(() => ({}));

  if (body.action === 'regenerate') {
    const settings = await saveGoogleAdsLeadSettings({ webhookKey: generateWebhookKey(), regeneratedAt: new Date().toISOString() });
    return Response.json(publicSettings(settings));
  }

  if (typeof body.enabled === 'boolean') {
    const settings = await saveGoogleAdsLeadSettings({ enabled: body.enabled });
    return Response.json(publicSettings(settings));
  }

  return Response.json({ error: 'Nothing to update.' }, { status: 400 });
}
